# Generated by Django 5.1.4 on 2024-12-14 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Lost', 'Lost'), ('Found', 'Found')], max_length=100)),
                ('image', models.ImageField(upload_to='item_images/')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Personal Items', 'Personal'), ('School Items', 'School'), ('Electronics', 'Electronics'), ('Books and Educational Items', 'Educational'), ('Sports Items', 'Sports'), ('Food and Drink Containers', 'Foodanddrink'), ('Miscellaneous', 'Miscellaneous'), ('Identification and Documents', 'Identification')], max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('location', models.CharField(choices=[('Gusaling Villegas', 'Gv'), ('Gusaling Lacson', 'Gl'), ('Gusaling Maynila', 'Gm'), ('Gusaling Raja Soliman', 'Grs'), ('College of Law, College of Nursing', 'Cln'), ('Physical Therapy', 'Pt'), ('University Chapel', 'Uc'), ('Flame Monument', 'Fm'), ('Tanghalang Bayan', 'Tb'), ('Parade Ground', 'Pg'), ('Canteen', 'Cn'), ('University Activity Center', 'Uac')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('returned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='returned_items', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reported_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='harifind_app.item')),
            ],
        ),
    ]
