# Generated by Django 5.1.4 on 2024-12-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harifind_app', '0002_alter_item_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
