# Generated by Django 5.1.4 on 2024-12-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harifind_app', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='latest_comment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
