# Generated by Django 5.1.4 on 2024-12-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harifind_app', '0004_item_latest_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='latest_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
