# Generated by Django 5.1.4 on 2024-12-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harifind_app', '0007_item_found_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='returned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
